SELECT
  Case When log.REFERENCE Is Null Then Concat(CT.CT_ID, CT.TD_ID, CT.CP_ID) Else log.reference END  As id,
  CT.NAME_ As 'name',
  CT.LOG_SID As logsid,
  ls2.NAME_ As actionPlan,
  ct.is_critical As 'priority',
  ls.NAME_ As 'status',    
  CT.ENTITY_NAME As entity,
  Concat(FYP.NAME_, ' ', FY.NAME_) As closePeriod,
  CP.START_DATE As startDate,
  CT.DUE_DATE As dueDate,
  Concat (ap.first, ' ', AP.LAST) As owner,
  CASE WHEN AP3.USER_ID IS Null THEN null ELSE Concat (AP3.FIRST, ' ', AP3.LAST) END As approver,
  CASE WHEN AP4.USER_ID IS NULL THEN null ELSE Concat (AP4.FIRST, ' ', AP4.LAST) END As reviewer,
  CASE WHEN CT.COMPLETED IS NULL THEN 'false' ELSE 'true' End As completed
    FROM
        CL_TASK CT
        LEFT OUTER JOIN ASSIGN_PERSON AP ON CT.PERFORMER_ID = AP.PE_ID
        LEFT OUTER JOIN LOV_SYS LS ON CT.STATUS_LOV_ID = LS.LS_ID
        LEFT OUTER JOIN LOV_SYS LS1 ON CT.CL_TYPE_LOV_ID = LS1.LS_ID
        LEFT OUTER JOIN CL_TASK_D TD ON CT.TD_ID = TD.TD_ID
        INNER JOIN CL_PERIOD CP ON CT.CP_ID = CP.CP_ID
        INNER JOIN FISCAL_YR_PERIODS FYP ON CP.FYP_ID = FYP.FYP_ID
        INNER JOIN FISCAL_YEARS FY ON FYP.FY_ID = FY.FY_ID
        LEFT OUTER JOIN demo_LOG LOG ON CT.LOG_SID = LOG.SID
        LEFT OUTER JOIN FORM_LIST LIS ON LOG.FORM_LIST_SID = LIS.SID
        LEFT OUTER JOIN demo_TRANS TRA ON LOG.LAST_ROUTE_TRANS = TRA.SID
        LEFT OUTER JOIN ASSIGN_PERSON AP2 ON TRA.RECEIVER = AP2.USER_ID
        LEFT OUTER JOIN ASSIGN_PERSON AP3 ON CT.APPROVER_ID = AP3.PE_ID
        LEFT OUTER JOIN ASSIGN_PERSON AP4 ON CT.REVIEWER_ID = AP4.PE_ID
       Inner JOIN LOV_SYS LS2 ON CT.TYPE_LOV_ID = LS2.LS_ID
 